//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesSC
    {
        public int CategoriesSC_ID { get; set; }
        public int SC_ID { get; set; }
        public int Category_ID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ServiceCenter ServiceCenter { get; set; }
    }
}
