//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAccount
    {
        public int EmployeeAccount_ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public int Employee_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
