//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.Delivery = new HashSet<Delivery>();
            this.GoodsShops = new HashSet<GoodsShops>();
        }
    
        public int Good_ID { get; set; }
        public string Model { get; set; }
        public string Code { get; set; }
        public int Maker_ID { get; set; }
        public int Category_ID { get; set; }
        public decimal Price { get; set; }
        public decimal RevenuePrice { get; set; }
        public string Description { get; set; }
        public int GuaranteePeriod { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Delivery { get; set; }
        public virtual Makers Makers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsShops> GoodsShops { get; set; }
    }
}
