//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ServiceTransportation = new HashSet<ServiceTransportation>();
        }
    
        public int Service_ID { get; set; }
        public int Breakage_ID { get; set; }
        public int Status_ID { get; set; }
        public int Basket_ID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Breakage Breakage { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceTransportation> ServiceTransportation { get; set; }
    }
}
