//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int Shipment_ID { get; set; }
        public int Deliver_ID { get; set; }
        public int GoodsShops_ID { get; set; }
        public int Employee_ID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual GoodsShops GoodsShops { get; set; }
    }
}
