//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation
    {
        public int Transportation_ID { get; set; }
        public int GS_from_ID { get; set; }
        public int GS_in_ID { get; set; }
        public int Employee_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Count { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual GoodsShops GoodsShops { get; set; }
        public virtual GoodsShops GoodsShops1 { get; set; }
    }
}
